; Small C HuC6280 (v0.2, 08/Nov/97)
;
; Taken to HuC (22/Feb/00)
;
;
; This file generated by HuC (v3.21, 2005/04/09, Denki release)
; on Thu Sep 24 17:15:49 2015
;

HUC	= 1

	.include "startup.asm"
	.data
	.bank DATA_BANK

	.code

  .data
  .bank CONST_BANK
  .org $4400
 _sound_dat:
	dw	sound_data_table	; 0
	dw	loop_point_table	; 1
	dw	softenve_table		; 2
	dw	softenve_lp_table	; 3
	dw	pitchenve_table		; 4
	dw	pitchenve_lp_table	; 5
	dw	lfo_data		    ; 6
	dw	sound_data_bank		; 7
	dw	loop_point_bank		; 8
	dw	arpeggio_table		; 9
	dw	arpeggio_lp_table	; 10
    dw	dutyenve_table		; 11
    dw	dutyenve_lp_table	; 12
_pcewav:
	dw	pce_data_table
_xpcmdata
	dw	xpcm_data
;	.include "songdata.h"
	.bank CONST_BANK
	.include "effect.h"
;------------------------------
; PCM timer routines
	.code
	.bank START_BANK
; タイマー割り込みエントリーポイント
_timer_pcm
	pha
	phx
	phy
; C言語用一時変数などの保存
	__ldw <__temp
	__stw <__tmr_temp
	__ldw <__ptr
	__stw <__tmr_ptr
	__ldw <_bx
	__stw <__tmr_bx
	tma	#page(_pcm_intr)
	pha
	map	_pcm_intr
	jsr	_pcm_intr
	pla
	tam	#page(_pcm_intr)
; 一時変数などの復元
	__ldw <__tmr_temp
	__stw <__temp
	__ldw <__tmr_ptr
	__stw <__ptr
	__ldw <__tmr_bx
	__stw <_bx
; タイマー復帰
	sta   irq_status
	cli
	ply
	plx
	pla
	rti
; VSYNC割り込み
_vsync_drv
	__ldw <__temp
	__stw <__vs_temp
	__ldw <__ptr
	__stw <__vs_ptr
	__ldw <_bx
	__stw <__vs_bx
	tma	#page(_drv_intr)
	pha
	map	_drv_intr
	jsr	_drv_intr
	pla
	tam	#page(_drv_intr)
	__ldw <__vs_temp
	__stw <__temp
	__ldw <__vs_ptr
	__stw <__ptr
	__ldw <__vs_bx
	__stw <_bx
	rts
           .zp
__tmr_temp   .ds 2
__tmr_ptr   .ds 2
__tmr_bx    .ds 2
__vs_temp   .ds 2
__vs_ptr   .ds 2
__vs_bx    .ds 2
	; restore segment and bank
	.code
	.bank START_BANK
	.proc _pcm_play_data
	__pushw
	__ldwi	LL2
	__pushw
	__ldw_s	8
	  jmp	___case
LL4:

	__ldwi	_xpcm_addr
	__pushw
	__ldw_s	6
	__stwps
	__ldwi	_xpcm_len
	__pushw
	__ldw_s	4
	__stwps
	__ldwi	_xpcm_bank
	__pushw
	__ldb_s	2
	__stbps
	__ldwi	_xpcm_shift
	__pushw
	__ldwi	0
	__stbps
	__lbra	LL3
LL5:

	__ldwi	_xpcm_addr
	__addwi	2
	__pushw
	__ldw_s	6
	__stwps
	__ldwi	_xpcm_len
	__addwi	2
	__pushw
	__ldw_s	4
	__stwps
	__ldwi	_xpcm_bank
	__addwi	1
	__pushw
	__ldb_s	2
	__stbps
	__ldwi	_xpcm_shift
	__addwi	1
	__pushw
	__ldwi	0
	__stbps
	__lbra	LL3
	__lbra	LL3
LL2:

	.dw	5,LL4,4,LL5
	.dw	LL3,0
LL3:

	__ldw_s	6
	  call	_pcm_on
LL1:

	__addmi	8,__stack
	  rts
	.endp

	.proc _pcm_on
	__pushw
	__ldwi	2048
	__stw	_bx
	__ldb_s	0
	  call	_poke.2
	__ldwi	2052
	__stw	_bx
	__ldwi	223
	  call	_poke.2
	__ldwi	2048
	__stw	_bx
	__ldb	_reg_ch
	  call	_poke.2
	__ldb	_xpcm_play_flags
	__notw
	__tstw
	__lbeq	LL7
	  call	_ena_irq_tmr
LL7:

	__ldb_s	0
	__stw	<__temp
	__ldwi	5
	  jsr	eqzp
	__lbeq	LL8
	__ldb	_xpcm_play_flags
	__orwi	1
	  stx	_xpcm_play_flags
LL8:

	__ldb_s	0
	__stw	<__temp
	__ldwi	4
	  jsr	eqzp
	__lbeq	LL9
	__ldb	_xpcm_play_flags
	__orwi	2
	  stx	_xpcm_play_flags
LL9:

LL6:

	__addmi	2,__stack
	  rts
	.endp

	.proc _pcm_off
	__pushw
	__ldb_s	0
	__stw	<__temp
	__ldwi	5
	  jsr	eqzp
	__lbeq	LL11
	__ldb	_xpcm_play_flags
	__andwi	254
	  stx	_xpcm_play_flags
LL11:

	__ldb_s	0
	__stw	<__temp
	__ldwi	4
	  jsr	eqzp
	__lbeq	LL12
	__ldb	_xpcm_play_flags
	__andwi	253
	  stx	_xpcm_play_flags
LL12:

	__ldb	_xpcm_play_flags
	__notw
	__tstw
	__lbeq	LL13
	  call	_dis_irq_tmr
LL13:

LL10:

	__addmi	2,__stack
	  rts
	.endp

	.proc _pcm_stop
	__pushw
	__ldb_s	0
	  call	_pcm_off
LL14:

	__addmi	2,__stack
	  rts
	.endp

	.proc _pcm_check
	__pushw
	__ldb_s	0
	__stw	<__temp
	__ldwi	5
	  jsr	eqzp
	__lbeq	LL16
	__ldb	_xpcm_flags
	__andwi	1
	__lbra	LL15
LL16:

	__ldb_s	0
	__stw	<__temp
	__ldwi	4
	  jsr	eqzp
	__lbeq	LL17
	__ldb	_xpcm_flags
	__andwi	2
	__lbra	LL15
LL17:

	__ldwi	0
	__lbra	LL15
LL15:

	__addmi	2,__stack
	  rts
	.endp

	.proc _pcm_switch
	__pushw
	__ldb_s	0
	__tstw
	__lbeq	LL19
	__ldb_s	2
	__stw	<__temp
	__ldwi	5
	  jsr	eqzp
	__lbeq	LL20
	__ldb	_xpcm_flags
	__orwi	1
	  stx	_xpcm_flags
LL20:

	__ldb_s	2
	__stw	<__temp
	__ldwi	4
	  jsr	eqzp
	__lbeq	LL21
	__ldb	_xpcm_flags
	__orwi	2
	  stx	_xpcm_flags
LL21:

	__lbra	LL22
LL19:

	__ldb_s	2
	__stw	<__temp
	__ldwi	5
	  jsr	eqzp
	__lbeq	LL23
	__ldb	_xpcm_flags
	__andwi	254
	  stx	_xpcm_flags
LL23:

	__ldb_s	2
	__stw	<__temp
	__ldwi	4
	  jsr	eqzp
	__lbeq	LL24
	__ldb	_xpcm_flags
	__andwi	253
	  stx	_xpcm_flags
LL24:

LL22:

LL18:

	__addmi	4,__stack
	  rts
	.endp

	REG_SEL: .equ $0800
	REG_DAC: .equ $0806
	; _xpeeki_b <addr>
	;
	; in  : addr = address
	; out : reg.a
	.macro _xpeeki_b
		__ldwi	\1
		__stw	<__ptr
		lda		[__ptr]
	.endm
	; _xpeek_b <addr>
	;
	; in  : addr = address
	; out : reg.a
	.macro _xpeek_b
		__ldw	\1
		__stw	<__ptr
		lda		[__ptr]
	.endm
	; _xpokei_b <addr>
	;
	; in : addr = address
	;    : reg.a = value
	.macro _xpokei_b
		pha
		__ldwi	\1
		__stw	<__ptr
		pla
		sta		[__ptr]
	.endm	
	; _xpoke_b <addr>
	;
	; in : addr = address
	;    : reg.a = value
	.macro _xpoke_b
		pha
		__ldw	\1
		__stw	<__ptr
		pla
		sta		[__ptr]
	.endm
	;_pcm_proc < ch , index > 
	;
	; in : ch = 物理チャンネル
	;    : index = 変数の相対位置
	.macro _pcm_proc
		; チャンネル選択
		lda		#\1 
		_xpokei_b REG_SEL
		; バンク切り替え
		tma		#3
		sta		_xpcm_bank_save
		lda		_xpcm_bank + \2
		tam		#3
		; 4bitシフト
		lda		_xpcm_shift + \2
		beq		.high_\2
	.low_\2:
		_xpeek_b _xpcm_addr + (\2 * 2)
		asl		A
		and		#$1f
		pha
		__ldw   _xpcm_addr + (\2 * 2)
		__addwi 1
		__stw	_xpcm_addr + (\2 * 2)
		__ldw   _xpcm_len + (\2 * 2)
		__subwi 1
		__stw	_xpcm_len + (\2 * 2)
		pla
		jmp		.store_\2
	.high_\2:
		_xpeek_b _xpcm_addr + (\2 * 2)
		lsr		A
		lsr		A
		lsr		A
		and		#$1e
	.store_\2:
		; DACへ出力
		_xpokei_b REG_DAC
		; バンク切り替えを戻す
		lda		_xpcm_bank_save
		tam		#3
		; シフトフラグを反転
		lda		_xpcm_shift + \2
		eor		#1
		sta		_xpcm_shift + \2
		__ldw   _xpcm_len + (\2 * 2)
		stx		<__temp
		ora		<__temp
		bne		.end_\2
		; PCMをオフにする
		__ldwi	\1
		call	_pcm_off		
	.end_\2:
	.endm
	;
	; pcm_intr 
	;
	.proc _pcm_intr
		; 再生フラグチェックで各PCM再生
		lda		_xpcm_play_flags
		and		#$01
		beq		.end_ch1
		jmp		.ch1_proc	
	.end_ch1:
		lda		_xpcm_play_flags
		and		#$02
		beq		.end_ch2
		jmp		.ch2_proc
	.end_ch2:
		; チャンネルを戻して終了
		lda		_reg_ch
		_xpokei_b REG_SEL
		rts
	; process
	.ch1_proc:
		_pcm_proc 5,0
		jmp		.end_ch1
	.ch2_proc:
		_pcm_proc 4,1
		jmp		.end_ch2
	.endp
	; 割り込み有効
    .proc _ena_irq_tmr
	smb   #2,<irq_m
	rts
	.endp
	; 割り込み無効
    .proc _dis_irq_tmr
	rmb   #2,<irq_m
	rts
	.endp
	; 割り込みタイマー設定
	.proc _set_pcmintr
	stz   irq_status
	stw   #_timer_pcm,timer_jmp
	rmb   #2,<irq_m
	; V = 1
	; (7.159090 / 1024) / V = 6991.29Hz
	lda   #0
	sta   timer_cnt
	lda   #$1
	sta   timer_ctrl
	cli
	rts
	.endp
	; PCMバンク
	.proc _chg_pcmbank
	txa
	tam #3
	rts
	.endp
	.proc _init_pcmdrv
	__addmi	-2,__stack
	__stwi_s	0,0
LL26:

	__ldw_s	0
	__stw	<__temp
	__ldwi	2
	  jsr	ltzp
	__lbne	LL28
	__lbra	LL29
LL27:

	__ldw_s	0
	__incw_s	0
	__lbra	LL26
LL28:

	__ldw_s	0
	__aslw
	__addwi	_xpcm_addr
	__pushw
	__ldw_s	2
	__aslw
	__addwi	_xpcm_len
	__pushw
	__ldwi	0
	__stwps
	__stwps
	__ldwi	_xpcm_shift
	__addw_s	0
	__pushw
	__ldwi	_xpcm_bank
	__addw_s	2
	__pushw
	__ldwi	0
	__stbps
	__stbps
	__lbra	LL27
LL29:

	__ldwi	0
	  stx	_xpcm_play_flags
	__ldwi	0
	  stx	_xpcm_flags
	  call	_set_pcmintr
LL25:

	__addmi	2,__stack
	  rts
	.endp

	.proc _chg_cbank
	txa
	tam #2
	rts
	.endp
	.proc _now_cbank
	tma #2
	tax
	cla
	rts
	.endp
	.proc _def_cbank
	lda #CONST_BANK+_bank_base
	tam #2
	rts
	.endp
	.proc _drv_setintr
	stw   #_vsync_drv,vsync_hook
	smb   #4,<irq_m		; enable new code
	smb   #5,<irq_m		; disable system card code
	rts
	.endp
	.proc _mixvol
	__pushw
	__ldb	_reg_ch
	  call	_pcm_check
	__tstw
	__lbeq	LL31
	__ldwi	2052
	__stw	_bx
	__ldwi	192
	__pushw
	__ldb_s	2
	__orws
	  call	_poke.2
	__lbra	LL30
LL31:

	__ldb_s	0
	__tstw
	__lbeq	LL32
	__ldb_s	0
	__orwi	128
	__stb_s	0
LL32:

	__ldwi	2052
	__stw	_bx
	__ldb_s	0
	  call	_poke.2
	__ldwi	_ch_lastvol
	__pushw
	__ldb	_reg_ch
	__addws
	__pushw
	__ldb_s	2
	__stbps
LL30:

	__addmi	2,__stack
	  rts
	.endp

	.proc _snd_saw
	__pushw
	__addmi	-1,__stack
	__ldwi	2052
	__stw	_bx
	__ldwi	0
	  call	_poke.2
	__stbi_s	0,0
LL34:

	__ldb_s	0
	__stw	<__temp
	__ldwi	32
	  jsr	ltzp
	__lbne	LL36
	__lbra	LL37
LL35:

	__ldb_s	0
	__addwi	1
	__stb_s	0
	__subwi	1
	__lbra	LL34
LL36:

	__ldwi	2054
	__stw	_bx
	__ldb_s	0
	  call	_poke.2
	__lbra	LL35
LL37:

	__ldwi	2053
	__stw	_bx
	__ldwi	_panpod
	__addw_s	1
	__ldb_p
	  call	_poke.2
	__ldwi	2052
	__stw	_bx
	__ldwi	128
	  call	_poke.2
LL33:

	__addmi	3,__stack
	  rts
	.endp

	.proc _snd_chg
	__pushw
	__addmi	-4,__stack
	__ldwi	_pcewav
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw_s	6
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stw_s	0
	__ldwi	2052
	__stw	_bx
	__ldwi	0
	  call	_poke.2
	__stwi_s	0,2
LL39:

	__ldw_s	2
	__stw	<__temp
	__ldwi	32
	  jsr	ltzp
	__lbne	LL41
	__lbra	LL42
LL40:

	__ldw_s	2
	__incw_s	2
	__lbra	LL39
LL41:

	__ldwi	2054
	__stw	_bx
	__ldw_s	0
	__ldb_p
	  call	_poke.2
	__ldw_s	0
	__incw_s	0
	__lbra	LL40
LL42:

	__ldwi	_ch_lastvol
	__pushw
	__ldb	_reg_ch
	__addws
	__ldb_p
	__stw_s	2
	__ldwi	2052
	__stw	_bx
	__ldw_s	2
	  call	_poke.2
LL38:

	__addmi	6,__stack
	  rts
	.endp

	.proc _drv_init
	__addmi	-4,__stack
	  call	_now_cbank
	  stx	_ch_topbank
	__ldwi	4660
	__stw	_seq_ptr
	__stwi_s	0,2
LL44:

	__ldw_s	2
	__stw	<__temp
	__ldwi	6
	  jsr	ltzp
	__lbne	LL46
	__lbra	LL47
LL45:

	__ldw_s	2
	__incw_s	2
	__lbra	LL44
LL46:

	__ldw_s	2
	  stx	_reg_ch
	__ldwi	2048
	__stw	_bx
	__ldw_s	2
	  call	_poke.2
	__ldwi	_tone_sw
	__addw_s	2
	__pushw
	__ldwi	255
	__stbps
	__ldwi	_lfo_sw
	__addw_s	2
	__pushw
	__ldwi	255
	__stbps
	__ldwi	_note_sw
	__addw_s	2
	__pushw
	__ldwi	255
	__stbps
	__ldwi	_panpod
	__addw_s	2
	__pushw
	__ldwi	255
	__stbps
	__ldwi	_pitch_sw
	__addw_s	2
	__pushw
	__ldwi	255
	__stbps
	__ldw_s	2
	__aslw
	__addwi	_seq_pos
	__pushw
	__ldwi	_sound_dat
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw_s	6
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stwps
	__ldwi	_loop_cnt
	__addw_s	2
	__pushw
	__ldwi	0
	__stbps
	__ldwi	_detune
	__addw_s	2
	__pushw
	__ldwi	0
	__stbps
	__ldw_s	2
	__aslw
	__addwi	_tone_envadr
	__pushw
	__ldwi	0
	__stwps
	__ldw_s	2
	__aslw
	__addwi	_note_envadr
	__pushw
	__ldwi	0
	__stwps
	__ldw_s	2
	__aslw
	__addwi	_pitch_envadr
	__pushw
	__ldwi	0
	__stwps
	__ldw_s	2
	__aslw
	__addwi	_volume_envadr
	__pushw
	__ldwi	0
	__stwps
	__ldwi	_ch_bank
	__addw_s	2
	__pushw
	__ldwi	_sound_dat
	__addwi	14
	__stw	__ptr
	__ldwp	__ptr
	__addw_s	4
	__stw	__ptr
	__ldwp	__ptr
	__stbps
	__ldw_s	2
	  call	_snd_saw
	__ldwi	_ch_cnt
	__addw_s	2
	__pushw
	__ldwi	0
	__stbps
	__ldwi	_ch_efx
	__addw_s	2
	__pushw
	__ldwi	0
	__stbps
	__ldwi	_ch_lastvol
	__addw_s	2
	__pushw
	__ldwi	0
	__stbps
	__lbra	LL45
LL47:

	__stwi_s	0,2
LL48:

	__ldw_s	2
	__stw	<__temp
	__ldwi	2
	  jsr	ltzp
	__lbne	LL50
	__lbra	LL51
LL49:

	__ldw_s	2
	__incw_s	2
	__lbra	LL48
LL50:

	__ldwi	_noise_sw
	__addw_s	2
	__pushw
	__ldwi	0
	__stbps
	__ldwi	_noise_freq
	__addw_s	2
	__pushw
	__ldwi	0
	__stbps
	__lbra	LL49
LL51:

	__ldwi	2049
	__stw	_bx
	__ldwi	255
	  call	_poke.2
	  call	_init_pcmdrv
	  call	_drv_setintr
LL43:

	__addmi	4,__stack
	  rts
	.endp

	.proc _set_vol
	__pushw
	__ldw_s	0
	__andwi	128
	__tstw
	__lbeq	LL53
	__ldw_s	2
	__aslw
	__addwi	_volume_envadr
	__pushw
	__ldwi	0
	__stwps
	__ldw_s	0
	__andwi	31
	  call	_mixvol
	__lbra	LL54
LL53:

	__ldw_s	0
	__andwi	127
	__stw_s	0
	__ldb	_ch_topbank
	  call	_chg_cbank
	__ldw_s	2
	__aslw
	__addwi	_volume_envadr
	__pushw
	__ldwi	_sound_dat
	__addwi	4
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw_s	4
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stwps
	__ldb	_ch_nowbank
	  call	_chg_cbank
LL54:

LL52:

	__addmi	4,__stack
	  rts
	.endp

	.proc _set_note
	__pushw
	__addmi	-1,__stack
	__ldb_s	1
	__addwi	3
	__andwi	15
	__stb_s	0
	__ldwi	_seq_freq
	__pushw
	__ldb_s	5
	__aslw
	__addws
	__pushw
	__ldwi	_freq
	__pushw
	__ldb_s	4
	__andwi	15
	__aslw
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldb_s	5
	__pushw
	__ldwi	4
	  jsr	asr
	  jsr	asr
	__stwps
LL55:

	__addmi	5,__stack
	  rts
	.endp

	.proc _do_seq
	__pushw
	__addmi	-10,__stack
	__ldb	_ch_nowbank
	  call	_chg_cbank
LL57:

	__ldwi	1
	__tstw
	__lbeq	LL58
;
; start command loop (do_seq)
;
	__ldwi	_ch_cnt
	__addw_s	10
	__ldb_p
	__tstw
	__lbeq	LL59
	__lbra	LL56
LL59:

	__ldw	_seq_ptr
	__ldb_p
	__stw_s	8
	__ldwi	_ch_lastcmd
	__addw_s	10
	__pushw
	__ldw_s	10
	__stbps
;
; check key on
;
	__ldw_s	8
	__stw	<__temp
	__ldwi	144
	  jsr	ltzp
	__lbeq	LL60
	__lbra	LL58
LL60:

	__ldw_s	8
	__stw	<__temp
	__ldwi	232
	  jsr	gezp
	__lbeq	LL61
	__ldwi	_seqproc
	__pushw
	__ldw_s	10
	__subwi	232
	__aslw
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stw_s	0
;
; jump to command routine
; sax
  pha
  sax
  pha
  rts
SEQ_FF:
  nop
	__ldb	_ch_topbank
	  call	_chg_cbank
	__ldwi	_sound_dat
	__addwi	2
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw_s	12
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stw	_seq_ptr
	__ldwi	_sound_dat
	__addwi	16
	__stw	__ptr
	__ldwp	__ptr
	__addw_s	10
	__stw	__ptr
	__ldwp	__ptr
	  stx	_ch_nowbank
	__ldb	_ch_nowbank
	  call	_chg_cbank
		jmp endpoint
SEQ_FE:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldw_s	4
	__stw	<__temp
	__ldwi	128
	  jsr	gezp
	__lbeq	LL62
	__stwi_s	255,4
LL62:

	__ldwi	_tone_sw
	__addw_s	10
	__pushw
	__ldw_s	6
	__stbps
	__ldw_s	10
	  call	_reset_te
	jmp endpoint
SEQ_F9:
  nop
	__ldw	_seq_ptr
	__addwi	2
	__stw	_seq_ptr
	jmp endpoint
SEQ_FD:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	_ch_vol
	__addw_s	10
	__pushw
	__ldw_s	6
	__stbps
	__ldw_s	10
	__pushw
	__ldw_s	6
	  call	_set_vol
	jmp endpoint
SEQ_FC:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	0
	  call	_mixvol
	__ldb	_reg_ch
	  call	_pcm_check
	__tstw
	__lbeq	LL63
	__ldb	_reg_ch
	  call	_pcm_stop
LL63:

	__ldw_s	10
	__aslw
	__addwi	_volume_envadr
	__pushw
	__ldwi	0
	__stwps
	__ldwi	_ch_cnt
	__addw_s	10
	__pushw
	__ldw_s	6
	__stbps
	__lbra	LL56
	jmp endpoint
SEQ_FB:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	_lfo_sw
	__addw_s	10
	__pushw
	__ldw_s	6
	__stbps
	__ldw_s	10
	  call	_reset_lfo
	jmp endpoint
SEQ_FA:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldw_s	4
	__stw	<__temp
	__ldwi	255
	  jsr	eqzp
	__lbeq	LL64
	__ldwi	_detune
	__addw_s	10
	__pushw
	__ldwi	0
	__stbps
	__lbra	LL65
LL64:

	__ldwi	_detune
	__addw_s	10
	__pushw
	__ldw_s	6
	__stbps
LL65:

	jmp endpoint
SEQ_F8:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	_pitch_sw
	__addw_s	10
	__pushw
	__ldw_s	6
	__stbps
	__ldw_s	10
	  call	_reset_pe
	jmp endpoint
SEQ_F7:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	_note_sw
	__addw_s	10
	__pushw
	__ldw_s	6
	__stbps
	__ldw_s	10
	  call	_reset_ne
	jmp endpoint
SEQ_F4:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	_ch_cnt
	__addw_s	10
	__pushw
	__ldw_s	6
	__stbps
	jmp endpoint
SEQ_F2:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldw_s	10
	__stw	<__temp
	__ldwi	3
	  jsr	gtzp
	__lbeq	LL66
	__ldw_s	4
	__tstw
	__lbeq	LL67
	__ldwi	_noise_sw
	__pushw
	__ldw_s	12
	__subwi	4
	__addws
	__pushw
	__ldwi	1
	__stbps
	__lbra	LL68
LL67:

	__ldwi	_noise_sw
	__pushw
	__ldw_s	12
	__subwi	4
	__addws
	__pushw
	__ldwi	0
	__stbps
	__ldwi	2055
	__stw	_bx
	__ldwi	0
	  call	_poke.2
LL68:

LL66:

	jmp endpoint
SEQ_F1:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldb	_ch_topbank
	  call	_chg_cbank
	__ldw_s	4
	  call	_snd_chg
	__ldb	_ch_nowbank
	  call	_chg_cbank
	__ldwi	_tone_sw
	__addw_s	10
	__pushw
	__ldwi	255
	__stbps
	jmp endpoint
SEQ_F0:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	_panpod
	__addw_s	10
	__pushw
	__ldw_s	6
	__stbps
	__ldwi	2053
	__stw	_bx
	__ldw_s	4
	  call	_poke.2
	jmp endpoint
SEQ_EF:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldw_s	10
	__pushw
	__ldw_s	6
	  call	_pcm_switch
	jmp endpoint
SEQ_EE:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__pushw
	__ldw	_seq_ptr
	__addwi	1
	__ldb_p
	__pushw
	__ldwi	8
	  jsr	asl
	__orws
	__stw_s	2
	__stw	_seq_ptr
	__ldw_s	4
	  call	_chg_cbank
	__ldw_s	4
	  stx	_ch_nowbank
	jmp endpoint
SEQ_ED:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldw_s	4
	__stw	<__temp
	__ldwi	255
	  jsr	eqzp
	__lbeq	LL69
	__ldwi	2057
	__stw	_bx
	__ldwi	0
	  call	_poke.2
	__lbra	LL70
LL69:

	__ldwi	2057
	__stw	_bx
	__ldw_s	4
	__orwi	128
	  call	_poke.2
LL70:

	jmp endpoint
SEQ_EB:
	nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__ldwi	_ch_porthi
	__addw_s	10
	__pushw
	__ldw_s	6
	__stbps
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__ldwi	_ch_portlo
	__addw_s	10
	__pushw
	__ldw_s	6
	__stbps
	__ldwi	_ch_portcnt
	__addw_s	10
	__pushw
	__ldwi	0
	__stbps
	__ldwi	_ch_efx
	__addw_s	10
	__pushw
	__ldb_p
	__orwi	4
	__stbps
	__ldw	_seq_ptr
	incw	_seq_ptr
	jmp endpoint
SEQ_E9:
	nop
	__ldwi	_ch_efx
	__addw_s	10
	__pushw
	__ldb_p
	__orwi	1
	__stbps
	__ldw	_seq_ptr
	incw	_seq_ptr
	jmp endpoint
SEQ_EC:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	2056
	__stw	_bx
	__ldw_s	4
	  call	_poke.2
SEQ_E8:
SEQ_EA:
endpoint:
	__lbra	LL71
LL61:

	__ldw_s	8
	__stw	<__temp
	__ldwi	161
	  jsr	eqzp
	__lbeq	LL72
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	_loop_cnt
	__addw_s	10
	__ldb_p
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL73
	__ldwi	_loop_cnt
	__addw_s	10
	__pushw
	__ldwi	0
	__stbps
	__ldw	_seq_ptr
	__ldb_p
	__pushw
	__ldw	_seq_ptr
	__addwi	1
	__ldb_p
	__pushw
	__ldwi	8
	  jsr	asl
	__orws
	__stw_s	2
	__stw	_seq_ptr
	__lbra	LL74
LL73:

	__ldw	_seq_ptr
	__addwi	2
	__stw	_seq_ptr
LL74:

LL72:

	__ldw_s	8
	__stw	<__temp
	__ldwi	160
	  jsr	eqzp
	__lbeq	LL75
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldb_p
	__stw_s	0
	__ldw	_seq_ptr
	__ldb_p
	__pushw
	__ldw	_seq_ptr
	__addwi	1
	__ldb_p
	__pushw
	__ldwi	8
	  jsr	asl
	__orws
	__stw_s	2
	__ldw	_seq_ptr
	__addwi	2
	__stw	_seq_ptr
	__ldwi	_loop_cnt
	__addw_s	10
	__ldb_p
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL76
	__ldwi	_loop_cnt
	__addw_s	10
	__pushw
	__ldwi	0
	__stbps
	__lbra	LL77
LL76:

	__ldwi	_loop_cnt
	__addw_s	10
	__ldb_p
	__stw	<__temp
	__ldwi	1
	  jsr	gtzp
	__lbeq	LL78
	__ldwi	_loop_cnt
	__addw_s	10
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
	__lbra	LL79
LL78:

	__ldwi	_loop_cnt
	__addw_s	10
	__pushw
	__ldw_s	6
	__subwi	1
	__stbps
LL79:

	__ldw_s	2
	__stw	_seq_ptr
	__ldw_s	0
	  call	_chg_cbank
	__ldw_s	0
	  stx	_ch_nowbank
LL77:

LL75:

LL71:

	__lbra	LL57
LL58:

;
; start key-on process
;
	__ldwi	_note_data
	__addw_s	10
	__pushw
	__ldw_s	10
	__stbps
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	_ch_cnt
	__addw_s	10
	__pushw
	__ldw_s	6
	__stbps
	__ldw_s	10
	  call	_pcm_check
	__tstw
	__lbeq	LL80
	__ldb	_ch_topbank
	  call	_chg_cbank
	__ldw	_xpcmdata
	__pushw
	__ldw_s	10
	__pushw
	__ldwi	3
	  jsr	asl
	__addws
	__stw_s	0
	__ldw_s	10
	__pushw
	__ldw_s	2
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw_s	4
	__addwi	2
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw_s	6
	__addwi	4
	__stw	__ptr
	__ldwp	__ptr
	  call	_pcm_play_data
	__ldb	_ch_nowbank
	  call	_chg_cbank
	__ldw_s	10
	__pushw
	__ldwi	_ch_vol
	__addw_s	12
	__ldb_p
	  call	_set_vol
	__lbra	LL56
LL80:

	__ldwi	_ch_efx
	__addw_s	10
	__ldb_p
	__andwi	1
	__notw
	__tstw
	__lbeq	LL81
	__ldw_s	10
	  call	_reset_te
	__ldw_s	10
	  call	_reset_ne
	__ldw_s	10
	  call	_reset_pe
	__ldw_s	10
	  call	_reset_lfo
LL81:

	__ldb	_ch_topbank
	  call	_chg_cbank
	__ldw_s	10
	__stw	<__temp
	__ldwi	3
	  jsr	gtzp
	__lbeq	LL83
	__ldwi	_noise_sw
	__pushw
	__ldw_s	12
	__subwi	4
	__addws
	__ldb_p
LL83:

	__boolw
	__tstw
	__lbeq	LL82
	__ldwi	_noise_freq
	__pushw
	__ldw_s	12
	__subwi	4
	__addws
	__pushw
	__ldw_s	10
	__andwi	31
	__stbps
	__ldwi	2055
	__stw	_bx
	__ldwi	128
	__pushw
	__ldw_s	10
	__andwi	31
	__orws
	  call	_poke.2
	__ldw_s	10
	__pushw
	__ldwi	_ch_vol
	__addw_s	12
	__ldb_p
	  call	_set_vol
	__ldb	_ch_nowbank
	  call	_chg_cbank
	__lbra	LL56
LL82:

	__ldw_s	10
	__pushw
	__ldw_s	10
	  call	_set_note
	__ldwi	_detune
	__addw_s	10
	__ldb_p
	__tstw
	__lbeq	LL84
	__ldwi	_detune
	__addw_s	10
	__ldb_p
	__andwi	128
	__tstw
	__lbeq	LL85
	__ldw_s	10
	__aslw
	__addwi	_seq_freq
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_detune
	__addw_s	14
	__ldb_p
	__andwi	127
	__subws
	__stwps
	__lbra	LL86
LL85:

	__ldw_s	10
	__aslw
	__addwi	_seq_freq
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_detune
	__addw_s	14
	__ldb_p
	__andwi	127
	__addws
	__stwps
LL86:

LL84:

	__ldwi	2051
	__stw	_bx
	__ldw_s	10
	__aslw
	__addwi	_seq_freq
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	8
	  jsr	asr
	__andwi	15
	  call	_poke.2
	__ldwi	2050
	__stw	_bx
	__ldw_s	10
	__aslw
	__addwi	_seq_freq
	__stw	__ptr
	__ldwp	__ptr
	__andwi	255
	  call	_poke.2
	__ldwi	_ch_efx
	__addw_s	10
	__ldb_p
	__andwi	1
	__notw
	__tstw
	__lbeq	LL87
	__ldw_s	10
	__pushw
	__ldwi	_ch_vol
	__addw_s	12
	__ldb_p
	  call	_set_vol
LL87:

	__ldwi	_ch_efx
	__addw_s	10
	__ldb_p
	__andwi	4
	__tstw
	__lbeq	LL88
	__ldwi	_ch_efx
	__addw_s	10
	__pushw
	__ldwi	_ch_efx
	__addw_s	12
	__ldb_p
	__pushw
	__ldwi	4
	__comw
	__andws
	__orwi	2
	__stbps
	__lbra	LL89
LL88:

	__ldwi	_ch_efx
	__addw_s	10
	__pushw
	__ldb_p
	__pushw
	__ldwi	6
	__comw
	__andws
	__stbps
LL89:

	__ldwi	_ch_efx
	__addw_s	10
	__pushw
	__ldb_p
	__pushw
	__ldwi	1
	__comw
	__andws
	__stbps
	__ldb	_ch_nowbank
	  call	_chg_cbank
LL56:

	__addmi	12,__stack
	  rts
	.endp

	.proc _reset_te
	__pushw
	__ldwi	_tone_sw
	__addw_s	0
	__ldb_p
	__stw	<__temp
	__ldwi	255
	  jsr	eqzp
	__lbeq	LL91
	__ldw_s	0
	__aslw
	__addwi	_tone_envadr
	__pushw
	__ldwi	0
	__stwps
	__lbra	LL92
LL91:

	__ldb	_ch_topbank
	  call	_chg_cbank
	__ldw_s	0
	__aslw
	__addwi	_tone_envadr
	__pushw
	__ldwi	_sound_dat
	__addwi	22
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_tone_sw
	__addw_s	4
	__ldb_p
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stwps
	__ldb	_ch_nowbank
	  call	_chg_cbank
LL92:

LL90:

	__addmi	2,__stack
	  rts
	.endp

	.proc _reset_ne
	__pushw
	__ldwi	_note_sw
	__addw_s	0
	__ldb_p
	__stw	<__temp
	__ldwi	255
	  jsr	eqzp
	__lbeq	LL94
	__ldw_s	0
	__aslw
	__addwi	_note_envadr
	__pushw
	__ldwi	0
	__stwps
	__lbra	LL95
LL94:

	__ldb	_ch_topbank
	  call	_chg_cbank
	__ldw_s	0
	__aslw
	__addwi	_note_envadr
	__pushw
	__ldwi	_sound_dat
	__addwi	18
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_note_sw
	__addw_s	4
	__ldb_p
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stwps
	__ldb	_ch_nowbank
	  call	_chg_cbank
LL95:

LL93:

	__addmi	2,__stack
	  rts
	.endp

	.proc _reset_pe
	__pushw
	__ldwi	_pitch_sw
	__addw_s	0
	__ldb_p
	__stw	<__temp
	__ldwi	255
	  jsr	eqzp
	__lbeq	LL97
	__ldw_s	0
	__aslw
	__addwi	_pitch_envadr
	__pushw
	__ldwi	0
	__stwps
	__lbra	LL98
LL97:

	__ldb	_ch_topbank
	  call	_chg_cbank
	__ldw_s	0
	__aslw
	__addwi	_pitch_envadr
	__pushw
	__ldwi	_sound_dat
	__addwi	8
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_pitch_sw
	__addw_s	4
	__ldb_p
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stwps
	__ldb	_ch_nowbank
	  call	_chg_cbank
LL98:

LL96:

	__addmi	2,__stack
	  rts
	.endp

	.proc _reset_lfo
	__pushw
	__ldwi	_lfo_sw
	__addw_s	0
	__ldb_p
	__stw	<__temp
	__ldwi	255
	  jsr	eqzp
	__lbeq	LL100
	__ldwi	_lfo_cnt
	__addw_s	0
	__pushw
	__ldwi	0
	__stbps
	__lbra	LL101
LL100:

	__ldb	_ch_topbank
	  call	_chg_cbank
	__ldwi	_lfo_step
	__addw_s	0
	__pushw
	__ldwi	0
	__stbps
	__ldwi	_lfo_cnt
	__addw_s	0
	__pushw
	__ldwi	_sound_dat
	__addwi	12
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_lfo_sw
	__addw_s	4
	__ldb_p
	__pushw
	__ldwi	2
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stbps
	__ldb	_ch_nowbank
	  call	_chg_cbank
LL101:

LL99:

	__addmi	2,__stack
	  rts
	.endp

_seqproc:
	dw   SEQ_E8
	dw   SEQ_E9
	dw   SEQ_EA
	dw	 SEQ_EB
	dw   SEQ_EC
	dw   SEQ_ED
	dw   SEQ_EE
	dw   SEQ_EF
	dw   SEQ_F0
	dw   SEQ_F1
	dw   SEQ_F2
	dw   endpoint ; f3
	dw   SEQ_F4
	dw   endpoint ; f5
	dw   endpoint ; f6
	dw   SEQ_F7   ; f7
	dw   SEQ_F8
	dw   SEQ_F9
	dw   SEQ_FA
	dw   SEQ_FB
	dw   SEQ_FC
	dw   SEQ_FD
	dw   SEQ_FE
	dw   SEQ_FF
	.proc _divxt
	__pushw
	__addmi	-4,__stack
	__stwi_s	0,0
	__stwi_s	0,2
LL103:

	__ldw_s	0
	__pushw
	__ldb_s	8
	  jsr	lt
	__lbne	LL105
	__lbra	LL106
LL104:

	__ldw_s	2
	__incw_s	2
	__lbra	LL103
LL105:

	__ldw_s	0
	__pushw
	__ldb_s	6
	__addws
	__stw_s	0
	__lbra	LL104
LL106:

	__ldw_s	2
	__lbra	LL102
LL102:

	__addmi	8,__stack
	  rts
	.endp

	.proc _drv_noteenv
	__pushw
	__addmi	-5,__stack
	__ldw_s	5
	__aslw
	__addwi	_note_envadr
	__stw	__ptr
	__ldwp	__ptr
	__stw	__ptr
	__ldwp	__ptr
	__stb_s	2
	__ldw_s	5
	__aslw
	__addwi	_note_envadr
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
	__ldb_s	2
	__stw	<__temp
	__ldwi	255
	  jsr	eqzp
	__lbeq	LL108
	__ldw_s	5
	__aslw
	__addwi	_note_envadr
	__pushw
	__ldwi	_sound_dat
	__addwi	20
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_note_sw
	__addw_s	9
	__ldb_p
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stwps
	__ldw_s	5
	__aslw
	__addwi	_note_envadr
	__stw	__ptr
	__ldwp	__ptr
	__stw	__ptr
	__ldwp	__ptr
	__stb_s	2
	__ldw_s	5
	__aslw
	__addwi	_note_envadr
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
LL108:

	__ldwi	_note_data
	__addw_s	5
	__ldb_p
	__stb_s	1
	__ldb_s	2
	__andwi	127
	__stb_s	0
	__pushw
	__ldwi	12
	  jsr	sdiv
	__pushw
	__ldwi	4
	  jsr	asl
	__stw_s	3
	__ldb_s	2
	__andwi	128
	__tstw
	__lbeq	LL109
	__ldb_s	1
	__pushw
	__ldw_s	5
	__subws
	__stb_s	1
	__ldb_s	0
	__pushw
	__ldwi	12
	  jsr	smod
	__stw_s	3
	__ldb_s	1
	__andwi	15
	__pushw
	__ldw_s	5
	  jsr	ge
	__lbeq	LL110
	__ldb_s	1
	__pushw
	__ldw_s	5
	__subws
	__stb_s	1
	__lbra	LL111
LL110:

	__ldb_s	1
	__subwi	4
	__stb_s	1
	__pushw
	__ldw_s	5
	__subws
	__stb_s	1
LL111:

	__lbra	LL112
LL109:

	__ldb_s	1
	__addw_s	3
	__stb_s	1
	__ldb_s	0
	__pushw
	__ldwi	12
	  jsr	smod
	__stw_s	3
	__ldb_s	1
	__addw_s	3
	__stb_s	1
	__andwi	15
	__stw	<__temp
	__ldwi	12
	  jsr	gezp
	__lbeq	LL113
	__ldb_s	1
	__addwi	4
	__stb_s	1
LL113:

LL112:

	__ldwi	_note_data
	__addw_s	5
	__pushw
	__ldb_s	3
	__stbps
	__ldw_s	5
	__pushw
	__ldb_s	3
	  call	_set_note
LL107:

	__addmi	7,__stack
	  rts
	.endp

	.proc _drv_toneenv
	__pushw
	__addmi	-3,__stack
	__ldw_s	3
	__aslw
	__addwi	_tone_envadr
	__stw	__ptr
	__ldwp	__ptr
	__stw	__ptr
	__ldwp	__ptr
	__stb_s	0
	__ldw_s	3
	__aslw
	__addwi	_tone_envadr
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
	__ldb_s	0
	__stw	<__temp
	__ldwi	255
	  jsr	eqzp
	__lbeq	LL115
	__ldw_s	3
	__aslw
	__addwi	_tone_envadr
	__pushw
	__ldwi	_sound_dat
	__addwi	24
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_tone_sw
	__addw_s	7
	__ldb_p
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stwps
	__ldw_s	3
	__aslw
	__addwi	_tone_envadr
	__stw	__ptr
	__ldwp	__ptr
	__stw	__ptr
	__ldwp	__ptr
	__stb_s	0
	__ldw_s	3
	__aslw
	__addwi	_tone_envadr
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
LL115:

	__ldb_s	0
	  call	_snd_chg
LL114:

	__addmi	5,__stack
	  rts
	.endp

	.proc _drv_pitchenv
	__pushw
	__addmi	-1,__stack
	__ldw_s	1
	__aslw
	__addwi	_pitch_envadr
	__stw	__ptr
	__ldwp	__ptr
	__stw	__ptr
	__ldwp	__ptr
	__stb_s	0
	__ldw_s	1
	__aslw
	__addwi	_pitch_envadr
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
	__ldb_s	0
	__stw	<__temp
	__ldwi	255
	  jsr	eqzp
	__lbeq	LL117
	__ldw_s	1
	__aslw
	__addwi	_pitch_envadr
	__pushw
	__ldwi	_sound_dat
	__addwi	10
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_pitch_sw
	__addw_s	5
	__ldb_p
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stwps
	__ldw_s	1
	__aslw
	__addwi	_pitch_envadr
	__stw	__ptr
	__ldwp	__ptr
	__stw	__ptr
	__ldwp	__ptr
	__stb_s	0
	__ldw_s	1
	__aslw
	__addwi	_pitch_envadr
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
LL117:

	__ldw_s	1
	__stw	<__temp
	__ldwi	3
	  jsr	gtzp
	__lbeq	LL119
	__ldwi	_noise_sw
	__pushw
	__ldw_s	3
	__subwi	4
	__addws
	__ldb_p
LL119:

	__boolw
	__tstw
	__lbeq	LL118
	__ldb_s	0
	__andwi	128
	__tstw
	__lbeq	LL120
	__ldwi	_noise_freq
	__pushw
	__ldw_s	3
	__subwi	4
	__addws
	__pushw
	__ldb_p
	__pushw
	__ldb_s	4
	__andwi	127
	__subws
	__stbps
	__lbra	LL121
LL120:

	__ldwi	_noise_freq
	__pushw
	__ldw_s	3
	__subwi	4
	__addws
	__pushw
	__ldb_p
	__pushw
	__ldb_s	4
	__addws
	__stbps
LL121:

	__ldwi	2055
	__stw	_bx
	__ldwi	128
	__pushw
	__ldwi	_noise_freq
	__pushw
	__ldw_s	5
	__subwi	4
	__addws
	__ldb_p
	__andwi	31
	__orws
	  call	_poke.2
LL118:

	__ldb_s	0
	__andwi	128
	__tstw
	__lbeq	LL122
	__ldw_s	1
	__aslw
	__addwi	_seq_freq
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldb_s	4
	__andwi	127
	__subws
	__stwps
	__lbra	LL123
LL122:

	__ldw_s	1
	__aslw
	__addwi	_seq_freq
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldb_s	4
	__addws
	__stwps
LL123:

LL116:

	__addmi	3,__stack
	  rts
	.endp

	.proc _drv_lfoseq
	__pushw
	__addmi	-2,__stack
	__ldwi	_sound_dat
	__addwi	12
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_lfo_sw
	__addw_s	4
	__ldb_p
	__pushw
	__ldwi	2
	  jsr	asl
	__addws
	__stw_s	0
	__ldwi	LL125
	__pushw
	__ldwi	_lfo_step
	__addw_s	4
	__ldb_p
	  jmp	___case
LL127:

	__ldwi	_lfo_cnt
	__addw_s	2
	__ldb_p
	__tstw
	__lbeq	LL128
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
	__lbra	LL129
LL128:

	__ldwi	_lfo_step
	__addw_s	2
	__pushw
	__ldwi	1
	__stbps
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldw_s	2
	__addwi	1
	__stw	__ptr
	__ldwp	__ptr
	__stbps
	__ldwi	_lfo_ct2
	__addw_s	2
	__pushw
	__ldw_s	2
	__addwi	1
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw_s	4
	__addwi	2
	__stw	__ptr
	__ldwp	__ptr
	  call	_divxt
	__stbps
	__ldwi	_lfo_stp
	__addw_s	2
	__pushw
	__ldwi	_lfo_ct2
	__addw_s	4
	__ldb_p
	__stbps
	__ldwi	_lfo_lev
	__addw_s	2
	__pushw
	__ldw_s	2
	__addwi	2
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw_s	4
	__addwi	1
	__stw	__ptr
	__ldwp	__ptr
	  call	_divxt
	__stbps
	__ldwi	_lfo_lev
	__addw_s	2
	__ldb_p
	__notw
	__tstw
	__lbeq	LL130
	__ldwi	_lfo_lev
	__addw_s	2
	__pushw
	__ldwi	1
	__stbps
LL130:

LL129:

	__lbra	LL126
LL131:

	__ldwi	_lfo_cnt
	__addw_s	2
	__ldb_p
	__tstw
	__lbeq	LL132
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
LL132:

	__ldwi	_lfo_ct2
	__addw_s	2
	__ldb_p
	__tstw
	__lbeq	LL133
	__ldwi	_lfo_ct2
	__addw_s	2
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
	__lbra	LL134
LL133:

	__ldw_s	2
	__aslw
	__addwi	_seq_freq
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_lfo_lev
	__addw_s	6
	__ldb_p
	__subws
	__stwps
	__ldwi	_lfo_ct2
	__addw_s	2
	__pushw
	__ldwi	_lfo_stp
	__addw_s	4
	__ldb_p
	__stbps
	__ldwi	_lfo_cnt
	__addw_s	2
	__ldb_p
	__notw
	__tstw
	__lbeq	LL135
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldw_s	2
	__addwi	1
	__stw	__ptr
	__ldwp	__ptr
	__stbps
	__ldwi	_lfo_step
	__addw_s	2
	__pushw
	__ldwi	2
	__stbps
LL135:

LL134:

	__lbra	LL126
LL136:

	__ldwi	_lfo_cnt
	__addw_s	2
	__ldb_p
	__tstw
	__lbeq	LL137
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
LL137:

	__ldwi	_lfo_ct2
	__addw_s	2
	__ldb_p
	__tstw
	__lbeq	LL138
	__ldwi	_lfo_ct2
	__addw_s	2
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
	__lbra	LL139
LL138:

	__ldw_s	2
	__aslw
	__addwi	_seq_freq
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_lfo_lev
	__addw_s	6
	__ldb_p
	__addws
	__stwps
	__ldwi	_lfo_ct2
	__addw_s	2
	__pushw
	__ldwi	_lfo_stp
	__addw_s	4
	__ldb_p
	__stbps
	__ldwi	_lfo_cnt
	__addw_s	2
	__ldb_p
	__notw
	__tstw
	__lbeq	LL140
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldw_s	2
	__addwi	1
	__stw	__ptr
	__ldwp	__ptr
	__stbps
	__ldwi	_lfo_step
	__addw_s	2
	__pushw
	__ldwi	3
	__stbps
LL140:

LL139:

	__lbra	LL126
LL141:

	__ldwi	_lfo_cnt
	__addw_s	2
	__ldb_p
	__tstw
	__lbeq	LL142
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
LL142:

	__ldwi	_lfo_ct2
	__addw_s	2
	__ldb_p
	__tstw
	__lbeq	LL143
	__ldwi	_lfo_ct2
	__addw_s	2
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
	__lbra	LL144
LL143:

	__ldw_s	2
	__aslw
	__addwi	_seq_freq
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_lfo_lev
	__addw_s	6
	__ldb_p
	__addws
	__stwps
	__ldwi	_lfo_ct2
	__addw_s	2
	__pushw
	__ldwi	_lfo_stp
	__addw_s	4
	__ldb_p
	__stbps
	__ldwi	_lfo_cnt
	__addw_s	2
	__ldb_p
	__notw
	__tstw
	__lbeq	LL145
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldw_s	2
	__addwi	1
	__stw	__ptr
	__ldwp	__ptr
	__stbps
	__ldwi	_lfo_step
	__addw_s	2
	__pushw
	__ldwi	4
	__stbps
LL145:

LL144:

	__lbra	LL126
LL146:

	__ldwi	_lfo_cnt
	__addw_s	2
	__ldb_p
	__tstw
	__lbeq	LL147
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
LL147:

	__ldwi	_lfo_ct2
	__addw_s	2
	__ldb_p
	__tstw
	__lbeq	LL148
	__ldwi	_lfo_ct2
	__addw_s	2
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
	__lbra	LL149
LL148:

	__ldw_s	2
	__aslw
	__addwi	_seq_freq
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_lfo_lev
	__addw_s	6
	__ldb_p
	__subws
	__stwps
	__ldwi	_lfo_ct2
	__addw_s	2
	__pushw
	__ldwi	_lfo_stp
	__addw_s	4
	__ldb_p
	__stbps
	__ldwi	_lfo_cnt
	__addw_s	2
	__ldb_p
	__notw
	__tstw
	__lbeq	LL150
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldw_s	2
	__addwi	1
	__stw	__ptr
	__ldwp	__ptr
	__stbps
	__ldwi	_lfo_step
	__addw_s	2
	__pushw
	__ldwi	1
	__stbps
LL150:

LL149:

	__lbra	LL126
	__lbra	LL126
LL125:

	.dw	0,LL127,1,LL131,2,LL136,3,LL141
	.dw	4,LL146
	.dw	LL126,0
LL126:

LL124:

	__addmi	4,__stack
	  rts
	.endp

	.proc _drv_intr
	__addmi	-6,__stack
	__ldwi	65534
	__stw	_seq_ptr
	__stwi_s	0,4
LL152:

	__ldw_s	4
	__stw	<__temp
	__ldwi	6
	  jsr	ltzp
	__lbne	LL154
	__lbra	LL155
LL153:

	__ldw_s	4
	__incw_s	4
	__lbra	LL152
LL154:

;
; TODO: check this
;
	__ldw_s	4
	  stx	_reg_ch
	__ldwi	2048
	__stw	_bx
	__ldw_s	4
	  call	_poke.2
	__ldwi	_ch_cnt
	__addw_s	4
	__ldb_p
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL156
	__ldw_s	4
	__aslw
	__addwi	_seq_pos
	__stw	__ptr
	__ldwp	__ptr
	__stw	_seq_ptr
	__ldwi	_ch_bank
	__addw_s	4
	__ldb_p
	  stx	_ch_nowbank
	__ldw_s	4
	  call	_do_seq
	__ldw_s	4
	__aslw
	__addwi	_seq_pos
	__pushw
	__ldw	_seq_ptr
	__stwps
	__ldwi	_ch_bank
	__addw_s	4
	__pushw
	__ldb	_ch_nowbank
	__stbps
	__ldb	_ch_topbank
	  call	_chg_cbank
LL156:

	__ldwi	_ch_cnt
	__addw_s	4
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
	__ldw_s	4
	__aslw
	__addwi	_volume_envadr
	__stw	__ptr
	__ldwp	__ptr
	__tstw
	__lbeq	LL157
	__ldw_s	4
	__aslw
	__addwi	_volume_envadr
	__stw	__ptr
	__ldwp	__ptr
	__stw	__ptr
	__ldwp	__ptr
	__stb_s	3
	__ldw_s	4
	__aslw
	__addwi	_volume_envadr
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
	__ldb_s	3
	__stw	<__temp
	__ldwi	255
	  jsr	eqzp
	__lbeq	LL158
	__ldwi	_ch_vol
	__addw_s	4
	__ldb_p
	__andwi	127
	__stb_s	3
	__ldw_s	4
	__aslw
	__addwi	_volume_envadr
	__pushw
	__ldwi	_sound_dat
	__addwi	6
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldb_s	7
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stwps
	__ldw_s	4
	__aslw
	__addwi	_volume_envadr
	__stw	__ptr
	__ldwp	__ptr
	__stw	__ptr
	__ldwp	__ptr
	__stb_s	3
	__ldw_s	4
	__aslw
	__addwi	_volume_envadr
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
LL158:

	__ldb_s	3
	__andwi	31
	  call	_mixvol
LL157:

	__stbi_s	0,2
	__ldw_s	4
	__aslw
	__addwi	_note_envadr
	__stw	__ptr
	__ldwp	__ptr
	__tstw
	__lbeq	LL159
	__stbi_s	1,2
	__ldw_s	4
	  call	_drv_noteenv
LL159:

	__ldw_s	4
	__aslw
	__addwi	_tone_envadr
	__stw	__ptr
	__ldwp	__ptr
	__tstw
	__lbeq	LL160
	__stbi_s	1,2
	__ldw_s	4
	  call	_drv_toneenv
LL160:

	__ldw_s	4
	__aslw
	__addwi	_pitch_envadr
	__stw	__ptr
	__ldwp	__ptr
	__tstw
	__lbeq	LL161
	__stbi_s	1,2
	__ldw_s	4
	  call	_drv_pitchenv
LL161:

	__ldwi	_lfo_sw
	__addw_s	4
	__ldb_p
	__stw	<__temp
	__ldwi	255
	  jsr	nezp
	__lbeq	LL162
	__stbi_s	1,2
	__ldw_s	4
	  call	_drv_lfoseq
LL162:

	__ldwi	_ch_efx
	__addw_s	4
	__ldb_p
	__andwi	2
	__tstw
	__lbeq	LL163
	__stbi_s	1,2
	__ldwi	_ch_porthi
	__addw_s	4
	__ldb_p
	__andwi	128
	__tstw
	__lbeq	LL164
	__ldwi	65280
	__pushw
	__ldwi	_ch_porthi
	__addw_s	6
	__ldb_p
	__orws
	__stw_s	0
	__lbra	LL165
LL164:

	__ldwi	_ch_porthi
	__addw_s	4
	__ldb_p
	__stw_s	0
LL165:

	__ldwi	_ch_portcnt
	__addw_s	4
	__pushw
	__ldb_p
	__pushw
	__ldwi	_ch_portlo
	__addw_s	8
	__ldb_p
	__andwi	127
	__addws
	__stbps
	__ldwi	_ch_portcnt
	__addw_s	4
	__ldb_p
	__andwi	128
	__tstw
	__lbeq	LL166
	__ldwi	_ch_portlo
	__addw_s	4
	__ldb_p
	__andwi	128
	__tstw
	__lbeq	LL167
	__ldw_s	0
	__subwi	1
	__stw_s	0
	__addwi	1
	__lbra	LL168
LL167:

	__ldw_s	0
	__incw_s	0
LL168:

	__ldwi	_ch_portcnt
	__addw_s	4
	__pushw
	__ldb_p
	__andwi	127
	__stbps
LL166:

	__ldw_s	4
	__aslw
	__addwi	_seq_freq
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addw_s	2
	__stwps
LL163:

	__ldb_s	2
	__tstw
	__lbeq	LL169
	__ldwi	2051
	__stw	_bx
	__ldw_s	4
	__aslw
	__addwi	_seq_freq
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	8
	  jsr	asr
	__andwi	15
	  call	_poke.2
	__ldwi	2050
	__stw	_bx
	__ldw_s	4
	__aslw
	__addwi	_seq_freq
	__stw	__ptr
	__ldwp	__ptr
	__andwi	255
	  call	_poke.2
LL169:

	__lbra	LL153
LL155:

LL151:

	__addmi	6,__stack
	  rts
	.endp

	.proc _main
	__addmi	-6,__stack
	__stwi_s	0,2
	  call	_disp_off
	  call	_cls
	__ldwi	1
	__stw	_color_reg
	__ldwi	7
	  stx	_al
	__ldwi	7
	  stx	_ah
	__ldwi	7
	  call	_set_color_rgb.4
	__ldwi	1
	  stx	_al
	__ldwi	0
	  call	_set_font_color.2
	__ldwi	0
	  call	_set_font_pal
	  call	_load_default_font
	  call	_disp_on
	__ldwi	LL0+0
	__phw	3,3
	__ldwi	5
	__phb	1
	__ldwi	2
	  call	_put_string.3
	  call	_drv_init
	__ldwi	LL0+14
	__phw	3,3
	__ldwi	5
	__phb	1
	__ldwi	3
	  call	_put_string.3
LL171:

	__ldwi	1
	__tstw
	__lbeq	LL172
	  ldy	#0
	  call	_vsync
	__ldw	_seq_ptr
	__phw	4,4
	__ldwi	4
	__phb	2
	__ldwi	13
	__phb	1
	__ldwi	3
	  call	_put_hex.4
	__ldb	_ch_topbank
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldwi	20
	__phb	1
	__ldwi	3
	  call	_put_hex.4
	__ldb	_ch_nowbank
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldwi	23
	__phb	1
	__ldwi	3
	  call	_put_hex.4
	__stwi_s	0,4
LL173:

	__ldw_s	4
	__stw	<__temp
	__ldwi	6
	  jsr	ltzp
	__lbne	LL175
	__lbra	LL176
LL174:

	__ldw_s	4
	__incw_s	4
	__lbra	LL173
LL175:

	__stwi_s	2,0
	__ldw_s	4
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldw_s	0
	__phb	1
	__ldwi	5
	__addw_s	4
	  call	_put_hex.4
	__ldw_s	0
	__addwi	3
	__stw_s	0
	__ldwi	_ch_lastcmd
	__addw_s	4
	__ldb_p
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldw_s	0
	__phb	1
	__ldwi	5
	__addw_s	4
	  call	_put_hex.4
	__ldw_s	0
	__addwi	3
	__stw_s	0
	__ldwi	_ch_cnt
	__addw_s	4
	__ldb_p
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldw_s	0
	__phb	1
	__ldwi	5
	__addw_s	4
	  call	_put_hex.4
	__ldw_s	0
	__addwi	3
	__stw_s	0
	__ldwi	_note_data
	__addw_s	4
	__ldb_p
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldw_s	0
	__phb	1
	__ldwi	5
	__addw_s	4
	  call	_put_hex.4
	__ldw_s	0
	__addwi	3
	__stw_s	0
	__ldwi	_ch_bank
	__addw_s	4
	__ldb_p
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldw_s	0
	__phb	1
	__ldwi	5
	__addw_s	4
	  call	_put_hex.4
	__ldw_s	0
	__addwi	3
	__stw_s	0
	__ldw_s	4
	__aslw
	__addwi	_seq_pos
	__stw	__ptr
	__ldwp	__ptr
	__phw	4,4
	__ldwi	4
	__phb	2
	__ldw_s	0
	__phb	1
	__ldwi	5
	__addw_s	4
	  call	_put_hex.4
	__ldw_s	0
	__addwi	5
	__stw_s	0
	__ldw_s	4
	__aslw
	__addwi	_seq_freq
	__stw	__ptr
	__ldwp	__ptr
	__phw	4,4
	__ldwi	4
	__phb	2
	__ldw_s	0
	__phb	1
	__ldwi	5
	__addw_s	4
	  call	_put_hex.4
	__ldw_s	0
	__addwi	5
	__stw_s	0
	__lbra	LL174
LL176:

	__stwi_s	0,4
LL177:

	__ldw_s	4
	__stw	<__temp
	__ldwi	2
	  jsr	ltzp
	__lbne	LL179
	__lbra	LL180
LL178:

	__ldw_s	4
	__incw_s	4
	__lbra	LL177
LL179:

	__stwi_s	1,0
	__ldw_s	4
	__aslw
	__addwi	_xpcm_addr
	__stw	__ptr
	__ldwp	__ptr
	__phw	4,4
	__ldwi	4
	__phb	2
	__ldw_s	0
	__phb	1
	__ldwi	14
	__addw_s	4
	  call	_put_hex.4
	__ldw_s	0
	__addwi	5
	__stw_s	0
	__ldw_s	4
	__aslw
	__addwi	_xpcm_len
	__stw	__ptr
	__ldwp	__ptr
	__phw	4,4
	__ldwi	4
	__phb	2
	__ldw_s	0
	__phb	1
	__ldwi	14
	__addw_s	4
	  call	_put_hex.4
	__lbra	LL178
LL180:

	__lbra	LL171
LL172:

LL170:

	__addmi	6,__stack
	  rts
	.endp

	.data
	.bank CONST_BANK
	.org $4000
LL0:
	.db	72,117,83,73,67,32,68,73
	.db	83,80,76,65,89,0,73,78
	.db	73,84,32,79,75,0
_freq:
	.dw	4068
	.dw	3839
	.dw	3624
	.dw	3420
	.dw	3228
	.dw	3047
	.dw	2876
	.dw	2715
	.dw	2562
	.dw	2419
	.dw	2283
	.dw	2155
	.dw	2034
	.dw	1920
	.dw	1812
	.dw	1710

	.bss
_reg_ch:		.ds	1
_ch_nowbank:		.ds	1
_ch_topbank:		.ds	1
_ch_lastcmd:		.ds	6
_ch_cnt:		.ds	6
_ch_vol:		.ds	6
_ch_bank:		.ds	6
_ch_lastvol:		.ds	6
_ch_efx:		.ds	6
_ch_porthi:		.ds	6
_ch_portlo:		.ds	6
_ch_portcnt:		.ds	6
_note_data:		.ds	6
_tone_sw:		.ds	6
_pitch_sw:		.ds	6
_note_sw:		.ds	6
_detune:		.ds	6
_panpod:		.ds	6
_loop_cnt:		.ds	6
_seq_ptr:		.ds	2
_seq_pos:		.ds	12
_seq_freq:		.ds	12
_tone_envadr:		.ds	12
_pitch_envadr:		.ds	12
_volume_envadr:		.ds	12
_note_envadr:		.ds	12
_lfo_sw:		.ds	6
_lfo_cnt:		.ds	6
_lfo_ct2:		.ds	6
_lfo_stp:		.ds	6
_lfo_lev:		.ds	6
_lfo_step:		.ds	6
_noise_freq:		.ds	2
_noise_sw:		.ds	2
_xpcm_addr:		.ds	4
_xpcm_len:		.ds	4
_xpcm_shift:		.ds	2
_xpcm_bank:		.ds	2
_xpcm_bank_save:		.ds	1
_xpcm_flags:		.ds	1
_xpcm_play_flags:		.ds	1
__arg:

;0 error(s) in compilation
;	literal pool:22
;	constant pool:32
;	global pool:2976
;	Macro pool:1359
